### ISSUE TITLE
获取https内容报错

### ISSUE THREAD

**Issue by xiaojianbj** [walkor/http-client#1]
是不是还不支持https，报错的内容如下：
SSL handshake error: stream_socket_enable_crypto(): SSL operation failed with code 1. OpenSSL Error messages:
error:14090086:SSL routines:ssl3_get_server_certificate:certificate verify failed 
Exception: Connection closed in /home/bdata/local/BData-service/vendor/workerman/http-client/src/Request.php:487
Stack trace:
#0 /home/bdata/local/BData-service/vendor/workerman/workerman/Connection/TcpConnection.php(949): Workerman\Http\Request->onUnexpectClose(Object(Workerman\Connection\AsyncTcpConnection))
#1 /home/bdata/local/BData-service/vendor/workerman/workerman/Connection/TcpConnection.php(776): Workerman\Connection\TcpConnection->destroy()
#2 /home/bdata/local/BData-service/vendor/workerman/workerman/Connection/TcpConnection.php(581): Workerman\Connection\TcpConnection->doSslHandshake(Resource id #31)
#3 /home/bdata/local/BData-service/vendor/workerman/workerman/Events/Select.php(294): Workerman\Connection\TcpConnection->baseRead(Resource id #31)
#4 /home/bdata/local/BData-service/vendor/workerman/workerman/Worker.php(2382): Workerman\Events\Select->loop()
#5 /home/bdata/local/BData-service/vendor/workerman/workerman/Worker.php(1490): Workerman\Worker->run()
#6 /home/bdata/local/BData-service/vendor/workerman/workerman/Worker.php(1320): Workerman\Worker::forkOneWorkerForLinux(Object(Workerman\Worker))
#7 /home/bdata/local/BData-service/vendor/workerman/workerman/Worker.php(1294): Workerman\Worker::forkWorkersForLinux()
#8 /home/bdata/local/BData-service/vendor/workerman/workerman/Worker.php(509): Workerman\Worker::forkWorkers()
#9 /home/bdata/local/BData-service/httpclient.php(40): Workerman\Worker::runAll()
#10 {main}SSL handshake error: stream_socket_enable_crypto(): SSL operation failed with code 1. OpenSSL Error messages:

**Comment by walkor** [comment]
支持https
看起来像是证书验证失败。

测试下百度或者其它网站https是否有问题。

**Comment by xiaojianbj** [comment]
就是用https://www.baidu.com测试的，程序直接用文档里写的范例，你可以试试

**Comment by xiaojianbj** [comment]
查了一下问题，在ConnectionPool.php的create方法中增加ssl参数的设置就行了，如下：
   /**
     * Create a connection.
     *
     * @param $address
     * @param bool $ssl
     * @return AsyncTcpConnection
     */
    protected function create($address, $ssl = false)
    {
        $context = array(
            'ssl' => array(
                'verify_peer' => false,
                'verify_peer_name'  => false,
                'allow_self_signed' => true
            )
        );
        $connection = new AsyncTcpConnection($address, $context);

**Comment by walkor** [comment]
我又测试了下，没问题。
从报错看是你的系统里的证书是ssl v3版本，ssl v3有严重的漏洞，所以在workerman代码里禁用了ssl v3.
如果证书有问题，curl应该也用不了，你可以测试下。用命令行测试 php test.php

**Comment by wanglong126** [comment]
> 查了一下问题，在ConnectionPool.php的create方法中增加ssl参数的设置就行了，如下： /** * Create a connection. * * @param $address * @param bool $ssl * @return AsyncTcpConnection */ protected function create($address, $ssl = false) { $context = array( 'ssl' => array( 'verify_peer' => false, 'verify_peer_name' => false, 'allow_self_signed' => true ) ); $connection = new AsyncTcpConnection($address, $context);

按照你的方法成功了,谢谢
