### ISSUE TITLE
Not receive a response until a timeout is reached

### ISSUE THREAD

**Issue by M0nik** [walkor/http-client#2]
Hello!
When I make a request, I don't receive a response until a timeout is reached. In Request.php, function checkComplete waits the connection to be closed if empty Content-Length. Why? For responses with a code of 200 and not empty response body everything works correctly, but if the answer is 401 or 201 with empty body, we are waiting for the closing.

**Comment by walkor** [comment]
Please show your codes or give an example to reproduce the issue.

> For response messages, whether or not a message-body is included with
   a message is dependent on both the request method and the response
   status code (section 6.1.1). All responses to the HEAD request method
   MUST NOT include a message-body, even though the presence of entity-
   header fields might lead one to believe they do. All 1xx
   (informational), 204 (no content), and 304 (not modified) responses
   MUST NOT include a message-body. All other responses do include a
   message-body, although it MAY be of zero length.

https://tools.ietf.org/html/rfc2616#section-4.3

According to the RFC specification, 201 and 401 do include a
   message-body although it MAY be of zero length. So if the status codes is 201 or 401 the head must include a `Message Length` field which can be `Transfer-Encoding` or `Content-Length` or `multipart/byteranges` or `By the server closing the connection` to tell the length of message-body.

**Comment by M0nik** [comment]
Example:
```php
<?php

require __DIR__ . '/vendor/autoload.php';

use Workerman\Http\Client;
use Workerman\Worker;

$worker = new Worker();
$worker->count = 1;

$worker->onWorkerStart = function () {
	$http_async_client = new Client( [
		'connect_timeout' => 10,
		'timeout'         => 10,
	] );
	$start_time = microtime( true );
	$http_async_client->get(
		"https://apip.orangedata.ru:2443/api/v2/devices/status/12345678910/Main",
		function () use ( $start_time ) {
			echo 'Elapsed time ' . round( microtime( true ) - $start_time, 2 ). ' sec';
		}
	);
};

Worker::runAll();
```
Output:
`Elapsed time 10.12 sec
`

**Comment by walkor** [comment]
Please upgrade to v1.0.6.

**Comment by M0nik** [comment]
Great, it works!
`Elapsed time 0.24 sec`

There is another issue. In the current implementation, it is not possible to set SSL certificates.
Now I've extended ConnectionPool and Client class and work as follows:
```php
protected function create($address, $ssl = false)
{
    $context = [];
    if ( !empty( $this->_option['context'] ) ) {
        $context = $this->_option['context'];
    }
    $connection = new AsyncTcpConnection($address, $context);
    ...
}
```

```php
$custom_http_client = new Client( [
  'connect_timeout' => 10,
  'timeout'         => 10,
  'context'         => [
    'ssl' => [
      'local_cert' => $this->client_crt_path,
      'local_pk'   => $this->client_key_path,
     ],
   ],
] );
```

What about native support?

**Comment by walkor** [comment]
Please upgrade again.

**Comment by M0nik** [comment]
Awesome! Thank you!
