### ISSUE TITLE
如何使用代理？

### ISSUE THREAD

**Issue by yuhengliang** [walkor/http-client#22]
请问请求如何使用代理服务器？

**Comment by walkor** [comment]
不支持代理&nbsp;


walkor
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Yu ***@***.***&gt;; 
发送时间: 2024年3月27日(星期三) 下午5:52
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; 
主题: [walkor/http-client] 如何使用代理？ (Issue #22)





 
请问请求如何使用代理服务器？

**Comment by roiwk** [comment]
等待大佬合并proxy的代码。   [proxy PR](https://github.com/walkor/http-client/pull/25) @yuhengliang

**Comment by osakey** [comment]
这个proxy 为啥不合并呢？

**Comment by roiwk** [comment]
大佬威武，瞬间合并master。   
这个proxy需要 workerman V5的版本(有相关workerman的PR)， 注意一下  @osakey
