### ISSUE TITLE
Wait for Http request

### ISSUE THREAD

**Issue by yuskamal** [walkor/http-client#3]
how to wait/await http-request ?

**Comment by walkor** [comment]
Sorry, http-client does not support wait/await.

**Comment by yuskamal** [comment]
function getPartnerService($postnya)
{   
   global $http_req;
   global $http_worker;

   $url = $http_worker->hostconfig["url"].":".$http_worker->hostconfig["port"].$http_worker->hostconfig["endpoint"];
   $auth = "Basic ".base64_encode($http_worker->hostconfig ["basic_auth_user"] . ":" . $http_worker->hostconfig ["basic_auth_pass"]);

   $http_req->request($url,['method' => 'POST',
            'headers' => ['Connection' => 'keep-alive',
                          'Authorization' => $auth,
                          'Content-type' => 'application/json'],
            'data'    => $postnya,
            'success' => function ($response)  {
                $body = $response->getBody(); // ==> Return to Caller Function
                }
            },
            'error' => function ($exception) {
                echo $exception;
            }
   ]);
}

It's possible return $response to caller function ?

**Comment by walkor** [comment]
> It's possible return $response to caller function ?

Sorry, http-client can't do this. I think you should use curl.

**Comment by yuskamal** [comment]
OK thanks

**Comment by eeliu** [comment]
@yuskamal 
I met the same problem. 
The only way can reach it is do the  wait/await logic in 'success' and 'error' callback.
