### ISSUE TITLE
Request.php 309行  echo $package,"\n";

### ISSUE THREAD

**Issue by 21307369** [walkor/http-client#31]
``` php 
<?php

namespace app\common;

use Monolog\Logger;
use Workerman\Http\Client;

class httpClient
{
    private static Client $client;

    public static function init(): void
    {
        if (!isset(self::$client)) {
            $options = [
//                'max_conn_per_addr' => 128,
//                'keepalive_timeout' => 10,
//                'connect_timeout' => 10,
//                'timeout' => 10,
            ];
            self::$client = new Client($options);
        }
    }

    /**
     * @param string $backUrl
     * @param array $data 
     * @return false
     * @throws \Throwable
     */
    public static function RequestPost(string $backUrl, array $data): bool
    {
        self::init();
        self::$client->post($backUrl, $data,
            function ($response) use ($data, $backUrl, $log) {
                $body = $response->getBody()->getContents();
                if ($response->getStatusCode() === 200 && $body === 'success') {
                    //等待异步通知
                   }
            },
            function ($exception) use ($data, $backUrl) { //异常处理
               
            }
        );
        return true;
    }
}
``` 
很奇怪我有2个地方使用RequestPost  我有2个应用 一个APP,一个admin APP请求正常,admin请求会在控制台输出
POST / HTTP/1.1
Host: xxxxxxx
User-Agent: workerman/http-client
Connection: keep-alive
Content-Type: application/x-www-form-urlencoded
Content-Length: 127

**Comment by walkor** [comment]
你好
有问题先尝试升级，如果还有问题再提问



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: 21307369 ***@***.***&gt;
发送时间: 2024年6月8日 10:34
收件人: walkor/http-client ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: Re: [walkor/http-client] Request.php 309行  echo $package,"\n"; (Issue #31)





 <?php namespace app\common; use Monolog\Logger; use Workerman\Http\Client; class httpClient {     private static Client $client;     public static function init(): void     {         if (!isset(self::$client)) {             $options = [ //                'max_conn_per_addr' =&gt; 128, //                'keepalive_timeout' =&gt; 10, //                'connect_timeout' =&gt; 10, //                'timeout' =&gt; 10,             ];             self::$client = new Client($options);         }     }     /**      * @param string $backUrl      * @param array $data      * @param Logger $log      * @return false      * @throws \Throwable      */     public static function RequestPost(string $backUrl, array $data): bool     {         self::init();         self::$client-&gt;post($backUrl, $data,             function ($response) use ($data, $backUrl, $log) {                 $body = $response-&gt;getBody()-&gt;getContents();                 if ($response-&gt;getStatusCode() === 200 &amp;&amp; $body === 'success') {                     //等待异步通知                    }             },             function ($exception) use ($data, $backUrl, $log) { //异常处理                             }         );         return true;     } }  
很奇怪我有2个地方使用RequestPost  前端请求正常,后端请求 控制台输出日志
 POST / HTTP/1.1
 Host: xxxxxxx
 User-Agent: workerman/http-client
 Connection: keep-alive
 Content-Type: application/x-www-form-urlencoded
 Content-Length: 127

**Comment by 21307369** [comment]
self::$client->post 外部包一个
try {
} 就不输出日志了.也是奇怪
