### ISSUE TITLE
SSL Verification

### ISSUE THREAD

**Issue by yuskamal** [walkor/http-client#5]
When access to https I got error message :
SSL handshake error: stream_socket_enable_crypto(): SSL operation failed with code 1. OpenSSL Error messages:
error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed

How to skip SSL verification ?

thx

**Comment by walkor** [comment]
Try add config context like this.
```php
$http = new Workerman\Http\Client([
    'context' => ['ssl' => [
      'verify_peer' => false,
      'verify_peer_name' => false,
      'allow_self_signed' => true
    ]]
]);
```

**Comment by yuskamal** [comment]
yesss, that's work

thank you
